#!/bin/bash

SITES_ENABLED=/private/etc/apache2/sites-enabled/

if [[ $EUID -ne 0 ]]; then
	echo >&2 "Can only be run as root"
	exit
fi

if [[ -z "$1" ]]; then
	echo >&2 "Usage: $0 SITE"
	exit
fi

site=$1

rm $SITES_ENABLED/$site
apachectl restart
